### ISSUE TITLE
Warning about variable perc_clyr

### ISSUE THREAD

**Issue by pletzer** [crazyzlj/SWAT#8]
Hi @crazyzlj 
On cray I get 

ftn-7212 crayftn: WARNING ORGNCSWAT2, File = ../../../scale_wlg_nobackup/filesets/nobackup/pletzera/swat/SWAT-pletzer/src/NCsed_leach.f90, Line = 215
  Variable "perc_clyr" is used before it is defined.

**Comment by crazyzlj** [comment]
Such WARNING is very common in SWAT. I have no idea if the developer team of SWAT has a plan to fix them thoroughly.
