### ISSUE TITLE
unit number outside allowed range

### ISSUE THREAD

**Issue by pletzer** [crazyzlj/SWAT#9]
Hi @crazyzlj 

On Cray I get the following runtime error:

lib-4013 : UNRECOVERABLE library error
  The unit number (101) in the OPEN statement must be nonnegative and outside
  the range of 100 through 102.

**Comment by crazyzlj** [comment]
The pull request has been merged to a new branch [RunOnCray](https://github.com/crazyzlj/SWAT/tree/RunOnCray).
